ptp4l: patches for compatibility with musl
* clock_adjtime() is provided in sys/timex.h instead of sys/time.h
* Fixes this error:

missing.h:66:19: error: static declaration of ‘clock_adjtime’ follows non-static declaration
 static inline int clock_adjtime(clockid_t id, struct timex *tx)
                   ^
In file included from missing.h:28:0,
                 from sja1105.c:30:
sysroot/usr/include/sys/timex.h:92:5: note: previous declaration of ‘clock_adjtime’ was here
 int clock_adjtime(clockid_t, struct timex *);

Signed-off-by: Vladimir Oltean <vladimir.oltean@nxp.com>